### ISSUE TITLE
Strange allocation and fail of example code r100 with strings

### ISSUE THREAD

**Issue by GanbaruTobi** [aemmitt-ns/radius#12]
The second example from the readme crashes with a huge allocation:
➜  radius git:(main) ✗ ./target/debug/radius2 -p tests/r100 -s stdin 96 -X Incorrect
memory allocation of 137421126912 bytes failed
[1]    4102 IOT instruction (core dumped)  ./target/debug/radius2 -p tests/r100 -s stdin 96 -X Incorrect

Or does one need to have 130gb free for allocation?

**Comment by aemmitt-ns** [comment]
No definitely should not need that much mem ever. I can't reproduce this, what OS and rust version are you running on?

**Comment by GanbaruTobi** [comment]
The OS is Arch, 
The rust versions are:
rustup 1.24.3 (2021-11-09)
info: The currently active `rustc` version is `rustc 1.59.0 (9d1b2106e 2022-02-23)
Toolchain: stable-x86_64-unknown-linux-gnu

Tested with:
➜  ~ r2 -v       
radare2 5.4.2 0 @ linux-x86-64 git.5.4.2
commit: unknown build: 2021-10-01__17:48:03

and
radare2 5.6.3 27504 @ linux-x86-64 git.5.6.2
commit: 79d108a4c2eac28ec36ce3aa7abd11142b1ee3a3 build: 2022-02-24__18:49:42

Can you tell me on what OS it worked for u?

**Comment by aemmitt-ns** [comment]
Yes it works on x86_64 linux for me. it should really work everywhere i have tried to avoid any os specific code. Is there any other context you can give me? RUST_BACKTRACE=full probably wont work cuz its not a panic.

**Comment by aemmitt-ns** [comment]
I was using rustc 1.56 but I just updated to 1.59.0 and the example still works. Can you open the core in gdb and give me the bt?

**Comment by GanbaruTobi** [comment]
Right now we found two arch systems on which it doesn't work, and one on which it does. We try to get closer to the problem. I got a first successful run when deinstalling radare2 from aur package (5.4.2) and taking the git version 5.6.3.

**Comment by GanbaruTobi** [comment]
Verified on two systems that with the newer r2 git version it works. So probably a error on my side that evaluation in comment 3 here didn't use newer r2 version.

gdb:
#0  0x00007fbd1340d34c in __pthread_kill_implementation () from /usr/lib/libc.so.6
#1  0x00007fbd133c04b8 in raise () from /usr/lib/libc.so.6
#2  0x00007fbd133aa534 in abort () from /usr/lib/libc.so.6
#3  0x0000561730f3e157 in std::sys::unix::abort_internal () at library/std/src/sys/unix/mod.rs:259
#4  0x0000561730c1e576 in std::process::abort () at library/std/src/process.rs:1980
#5  0x0000561730f379ce in std::alloc::rust_oom () at library/std/src/alloc.rs:330
#6  0x0000561730f55037 in alloc::alloc::__alloc_error_handler::__rg_oom () at library/alloc/src/alloc.rs:413
#7  0x0000561730f55027 in alloc::alloc::handle_alloc_error::rt_error () at library/alloc/src/alloc.rs:379
#8  0x0000561730f54ea7 in core::ops::function::FnOnce::call_once<fn(core::alloc::layout::Layout) -> !, (core::alloc::layout::Layout)> () at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/ops/function.rs:227
#9  0x0000561730f55216 in core::intrinsics::const_eval_select<(core::alloc::layout::Layout), fn(core::alloc::layout::Layout) -> !, fn(core::alloc::layout::Layout) -> !, !> () at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/intrinsics.rs:2345
#10 0x0000561730c1f916 in alloc::alloc::handle_alloc_error () at library/alloc/src/alloc.rs:383
#11 0x0000561730d29d7a in alloc::raw_vec::RawVec<radius2::value::Value, alloc::alloc::Global>::allocate_in<radius2::value::Value, alloc::alloc::Global> (capacity=0xfff77fe8, init=alloc::raw_vec::AllocInit::Uninitialized, alloc=...) at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/raw_vec.rs:190
#12 0x0000561730d2848c in alloc::raw_vec::RawVec<radius2::value::Value, alloc::alloc::Global>::with_capacity_in<radius2::value::Value, alloc::alloc::Global> (capacity=0xfff77fe8, alloc=...) at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/raw_vec.rs:132
#13 0x0000561730d05473 in alloc::vec::Vec<radius2::value::Value, alloc::alloc::Global>::with_capacity_in<radius2::value::Value, alloc::alloc::Global> (capacity=0xfff77fe8, alloc=...) at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/vec/mod.rs:609
#14 0x0000561730d04f36 in alloc::vec::Vec<radius2::value::Value, alloc::alloc::Global>::with_capacity<radius2::value::Value> (capacity=0xfff77fe8) at /rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/alloc/src/vec/mod.rs:470
#15 0x0000561730d1772a in radius2::memory::Memory::unpack (self=0x561731f7bec0, value=0x7ffd0cd83900, length=0xfff77fe8) at radius/src/memory.rs:630
#16 0x0000561730d159a2 in radius2::memory::Memory::write_value (self=0x561731f7bec0, addr=0x400639, value=0x7ffd0cd83900, length=0xfff77fe8) at radius/src/memory.rs:466
#17 0x0000561730d12719 in radius2::memory::Memory::write_sym (self=0x561731f7bec0, address=0x7ffd0cd838e0, value=0x7ffd0cd83900, len=0xfff77fe8, solver=0x561731f7b980) at radius/src/memory.rs:247
#18 0x0000561730ca82d0 in radius2::state::State::memory_write_value (self=0x561731f7b980, address=0x7ffd0cd838e0, value=0x7ffd0cd83900, length=0xfff77fe8) at radius/src/state.rs:436
#19 0x0000561730cc3d54 in radius2::operations::do_operation (state=0x561731f7b980, operation=0x561731f8f798) at radius/src/operations.rs:629
#20 0x0000561730c88b48 in radius2::processor::Processor::parse (self=0x7ffd0cda9910, state=0x561731f7b980, words=...) at radius/src/processor.rs:396
#21 0x0000561730c8c98e in radius2::processor::Processor::execute (self=0x7ffd0cda9910, state=0x561731f7b980, instr=0x561731fcf4d8, flags=0x561731fcf590, words=...) at radius/src/processor.rs:626
#22 0x0000561730c8d78f in radius2::processor::Processor::execute_instruction (self=0x7ffd0cda9910, state=0x561731f7b980, pc_val=0x400634) at radius/src/processor.rs:722
#23 0x0000561730c8d90c in radius2::processor::Processor::step (self=0x7ffd0cda9910, state=0x561731f7b980) at radius/src/processor.rs:734
#24 0x0000561730c8ecb3 in radius2::processor::Processor::run (self=0x7ffd0cda9910, state=..., mode=radius2::processor::RunMode::Single) at radius/src/processor.rs:839
#25 0x0000561730d5c70c in radius2::radius::Radius::run (self=0x7ffd0cda9810, state=..., _threads=0x1) at radius/src/radius.rs:468
#26 0x0000561730ccf41e in radius2::main () at radius/src/main.rs:589

valgrind:
memory allocation of 137421126912 bytes failed
==159582== 
==159582== Process terminating with default action of signal 6 (SIGABRT): dumping core
==159582==    at 0x4BA234C: __pthread_kill_implementation (in /usr/lib/libc.so.6)
==159582==    by 0x4B554B7: raise (in /usr/lib/libc.so.6)
==159582==    by 0x4B3F533: abort (in /usr/lib/libc.so.6)
==159582==    by 0x462156: std::sys::unix::abort_internal (mod.rs:259)
==159582==    by 0x142575: std::process::abort (process.rs:1980)
==159582==    by 0x45B9CD: rust_oom (alloc.rs:330)
==159582==    by 0x479036: __rg_oom (alloc.rs:413)
==159582==    by 0x479026: alloc::alloc::handle_alloc_error::rt_error (alloc.rs:379)
==159582==    by 0x478EA6: core::ops::function::FnOnce::call_once (function.rs:227)
==159582==    by 0x479215: core::intrinsics::const_eval_select (intrinsics.rs:2345)
==159582==    by 0x143915: alloc::alloc::handle_alloc_error (alloc.rs:383)
==159582==    by 0x24DD79: alloc::raw_vec::RawVec<T,A>::allocate_in (raw_vec.rs:190)

**Comment by aemmitt-ns** [comment]
hmm ok glad its working in some capacity. it should have worked with r2 5.4 though. gonna investigate a bit more, thanks for the backtrace

**Comment by aemmitt-ns** [comment]
Alright i think it must have been bad ESIL from that specific r2 version, combined with radius's different version of `=[]`. What is the output from running  `./target/debug/radius2 -p tests/r100 -s stdin 96 -X Incorrect -v` (or at least the last few lines)

**Comment by GanbaruTobi** [comment]
➜  radius git:(main) ✗ ./target/debug/radius2 -p tests/r100 -s stdin 96 -X Incorrect -v
0000000000400610:  xor ebp, ebp                             |  ebp,rbp,^,0xffffffff,&,rbp,=,$z,zf,:=,$p,pf,:=,31,$s,sf,:=,0,cf,:=,0,of,:=
0000000000400612:  mov r9, rdx                              |  rdx,r9,=
0000000000400615:  pop rsi                                  |  rsp,[8],rsi,=,8,rsp,+=
0000000000400616:  mov rdx, rsp                             |  rsp,rdx,=
0000000000400619:  and rsp, 0xfffffffffffffff0              |  18446744073709551600,rsp,&=,$z,zf,:=,$p,pf,:=,63,$s,sf,:=,0,cf,:=,0,of,:=
000000000040061d:  push rax                                 |  rax,8,rsp,-,=[8],8,rsp,-=
000000000040061e:  push rsp                                 |  rsp,8,rsp,-,=[8],8,rsp,-=
000000000040061f:  mov r8, 0x400900                         |  4196608,r8,=
0000000000400626:  mov rcx, 0x400890                        |  4196496,rcx,=
000000000040062d:  mov rdi, main                            |  4196328,rdi,=
0000000000400634:  call sym.imp.__libc_start_main           |  4195792,rip,8,rsp,-=,rsp,=[],rip,=
memory allocation of 137421126912 bytes failed
[1]    10994 IOT instruction (core dumped)  ./target/debug/radius2 -p tests/r100 -s stdin 96 -X Incorrect -v

**Comment by aemmitt-ns** [comment]
yeah thats what it was it was the `=[]`.I think it was removed from r2 and in radius i have it read the length from the stack. ill change that so it wont break on old r2 versions

**Comment by aemmitt-ns** [comment]
This should be fixed now, I readded PeekBits and PokeBits to perform `=[]` the way it (used to) be done in r2. Closing this now, thank you for submitting!
